### ISSUE TITLE
Generate UUID if it is not provided 

### ISSUE THREAD

**Issue by scheeles** [kubermatic/telemetry-client#4]
Let's generate the UUID and save it as secret if there is no UUID provided

**Comment by imharshita** [comment]
The probable solution is:

We can use this Helm uuidv4 function to genertate UUID https://helm.sh/docs/chart_template_guide/function_list/#uuid-functions 
But everytime  uuidv4 function is called, it will create a new random UUID

We may be able to get around the "only call uuidv4 once ever" problem by putting the value into a Secret, and then referencing it from elsewhere. This works only if the only place you use the UUID value is in an environment variable, or something else that can have a value injected from a secret.

We can do this by replacing https://github.com/kubermatic/kubermatic/blob/master/charts/telemetry/templates/secret.yaml#L22 with 
```
data:
  uuid: {{ .Values.telemetry.uuid | default uuidv4 | b64enc }}

```
and use it here https://github.com/kubermatic/kubermatic/blob/master/charts/telemetry/templates/cronjob.yaml#L71

**Comment by csengerszabo** [comment]
Sounds awesome! So the thing that needs to be decided is where we should store the Secret. Storing and referencing from environment variables could work?

**Comment by xrstf** [comment]
How would

```yaml
data:
  uuid: {{ .Values.telemetry.uuid | default uuidv4 | b64enc }}
```

not create a new secret everytime the chart is installed?

What about keeping the field as mandatory, but extending the KKP installer to handle to UUID creation. It could easily do a

```
if UUID not configured in helm; then
  get UUID secret from cluster
  if secret not exists; then
      create new UUID
      store in secret
      log info "created new UUID for your system"
  fi
  set helmvalues.telemetry.uuid=UUID
fi

continue with installation procedure
```

**Comment by xrstf** [comment]
The easiest solution would be to simply remove the option to specify the UUID in the helm chart and instead always generate it. Is there a reason to allow users to specify their own UUID?

**Comment by xrstf** [comment]
What do you mean by "checking the Helm values"? Yes, the UUID must not be mandatory in the chart anymore.

**Comment by imharshita** [comment]
> What do you mean by "checking the Helm values"? Yes, the UUID must not be mandatory in the chart anymore.

what I mean is we wont be able to do this:
```
if UUID not configured in helm; then
  get UUID secret from cluster
  ```

**Comment by imharshita** [comment]
thankyou @xrstf and @WeirdMachine. 
Tested the solution, it works perfectly and implemented here:  https://github.com/kubermatic/kubermatic/pull/9900
