### ISSUE TITLE
[Feature] Using IP2Location.io API as a failover for your geolocation needs

### ISSUE THREAD

**Issue by ip2location-com** [kubermatic/telemetry-client#43]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It helps to have a failover geolocation API in case your primary geolocation API fails.

[IP2Location.io API](https://www.ip2location.io/) gives you 500 IP queries per day if used without an API key.

When used with the free API plan key, you can query up to 30,000 IPs per month.

**Describe alternatives you've considered**

**Additional context**

**Comment by xrstf** [comment]
Please stop spamming GitHub.
